apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: {{ .Values.config.metadata.namespace | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: ops
  destination:
    namespace: ops
    server: {{ .Values.config.spec.destination.server | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: forgejo
    repoURL: code.forgejo.org/forgejo-helm
    targetRevision: 16.0.1
    helm:
      valuesObject:
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          tls:
          - hosts:
            - forge.stargrid.systems
            secretName: forge-tls
          hosts:
          - host: forge.stargrid.systems
            paths:
            - path: /
              pathType: Prefix
              port: http
        persistence:
          claimName: forgejo-shared-storage
          size: 10Gi
        signing:
          enabled: true
          existingSecret: forgejo-gpg-key
        # TODO: set up oauth with authentik
        # TODO: database
        gitea:
          additionalConfigSources:
          - secret:
              secretName: forgejo-mailer-config
          admin:
            existingSecret: forgejo-admin-user
            email: devops+forgejo@stargrid.systems
          config:
            APP_NAME: "STARGRID Forgejo"
            repository:
              DEFAULT_PRIVATE: private
              PREFERRED_LICENSES: AGPL-3.0-or-later
            repository.pull-request:
              DEFAULT_MERGE_STYLE: squash
              DEFAULT_UPDATE_STYLE: rebase
            cors:
              ENABLED: true
              ALLOW_DOMAIN: https://forge.stargrid.systems
            server:
              DOMAIN: forge.stargrid.systems
              ROOT_URL: https://forge.stargrid.systems/
              # TODO: ssh using hostPort?
              DISABLE_SSH: true
            openid:
              ENABLE_OPENID_SIGNUP: true
            oauth2_client:
              ENABLE_AUTO_REGISTRATION: true
              USERNAME: userid
              UPDATE_AVATAR: true
            service:
              DISABLE_REGISTRATION: true
              ENABLE_INTERNAL_SIGNIN: false
            session:
              COOKIE_NAME: stargrid_forgejo
            quota:
              ENABLED: true
            quota.default:
              TOTAL: 5G
          oauth:
          - name: "Nextcloud"
            provider: "nextcloud"
            existingSecret: forgejo-oauth-nextcloud
            useCustomUrls: true
            customAuthUrl: https://nextcloud.stargrid.systems/apps/oauth2/authorize
            customTokenUrl: https://nextcloud.stargrid.systems/apps/oauth2/api/v1/token
            customProfileUrl: https://nextcloud.stargrid.systems/ocs/v2.php/cloud/user?format=json
            skipLocal-2fa: true
