apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: {{ .Values.config.metadata.namespace | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: ops
  destination:
    namespace: ops
    server: {{ .Values.config.spec.destination.server | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: forgejo
    repoURL: code.forgejo.org/forgejo-helm
    targetRevision: 16.0.1
    helm:
      valuesObject:
        httpRoute:
          enabled: true
          hostnames:
          - forge.stargrid.systems
        persistence:
          size: 10Gi
        signing: {} # TODO: enable!
        gitea:
          config:
            server:
              DOMAIN: forge.stargrid.systems
              ROOT_URL: https://forge.stargrid.systems/
            service:
              DISABLE_REGISTRATION: true
