apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: {{ .Values.config.metadata.namespace | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: ops
  destination:
    namespace: ops
    server: {{ .Values.config.spec.destination.server | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.32.0
    helm:
      valuesObject: {}
